<a href="https://colab.research.google.com/github/shubhamrana3/numpy_task/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
x = np.array([200, 10, 50,70,80])
              
  
print("Size of the array: ", x.size)
  
print("Memory size of one array element in bytes: ", x.itemsize)
  

print("Memory size of numpy array in bytes:", x.size * x.itemsize)

Size of the array:  5
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 40


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
x = np.arange(10, 49)
x=x[::-1]
x

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
x =  np.arange(0, 9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
arr = np.array([1,2,0,0,4,0])
out_arr = arr[np.nonzero(arr)]
  
print ("Output array of non-zero number: ", out_arr) 

Output array of non-zero number:  [1 2 4]


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [6]:
x = np.eye(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [3]:
x = np.random.random((3,3,3))
x

array([[[0.36717136, 0.31284019, 0.41661692],
        [0.53324143, 0.36287661, 0.26695802],
        [0.81466834, 0.60059029, 0.87249067]],

       [[0.4406688 , 0.59065304, 0.83955477],
        [0.9950313 , 0.93674464, 0.96239871],
        [0.50976475, 0.06920461, 0.5674871 ]],

       [[0.11696746, 0.8645936 , 0.8888656 ],
        [0.67564926, 0.01349184, 0.36523447],
        [0.50326233, 0.90742876, 0.89881362]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [5]:
x = np.random.random((10,10))
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

[[0.69304854 0.68753404 0.59407994 0.95173804 0.51655981 0.4995783
  0.49976284 0.96571562 0.46708693 0.93905532]
 [0.40458079 0.19205147 0.61213734 0.18739024 0.86304928 0.61040224
  0.79284369 0.84816172 0.9661007  0.22521905]
 [0.26763271 0.293403   0.98452631 0.13761168 0.50208245 0.29262415
  0.20585644 0.06876688 0.48995393 0.22987787]
 [0.96402208 0.19038407 0.81613282 0.70791572 0.95986548 0.01368968
  0.39242943 0.33441372 0.87232961 0.26399328]
 [0.558015   0.29782804 0.00684685 0.61390964 0.33795225 0.80210332
  0.34288304 0.96608309 0.55388401 0.70761067]
 [0.20452087 0.00481856 0.22797893 0.3565605  0.3099392  0.30840477
  0.138002   0.07359952 0.1218404  0.4939756 ]
 [0.81681674 0.28527658 0.42774418 0.83036469 0.21689657 0.56641594
  0.97238318 0.90952466 0.89353854 0.80805077]
 [0.51542018 0.32567655 0.21120166 0.81852583 0.53694825 0.91752187
  0.6677424  0.54070383 0.89075254 0.89398558]
 [0.32527958 0.03064922 0.90803967 0.68100703 0.1992352  0.90314275
  0.42128478 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [7]:

x = np.random.random(10)
Mean = x.mean()
print (Mean)



0.43211534817277863


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [9]:
x = np.ones((10,10))
x[1:-1,1:-1]=0
x


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [11]:
x = np.ones((3,3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
x

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [12]:

x = np.diag(1+np.arange(4), k = -1)
print (x)



[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [13]:
x = np.zeros ((8,8), dtype=int)
x[1::2, ::2]= 1
x[::2, 1::2] = 1
print (x)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [14]:
print (np.unravel_index(100, (6,7,8)))



(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [15]:
array= np.array([[0,1], [1,0]])
x = np.tile(array,(4,4))
print (x)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [16]:
x = np.random.random((5,5))
xmax, xmin = x.max(), x.min()
x= (x-xmin)/(xmax-xmin)
x



array([[0.79241581, 0.69733607, 0.99188389, 0.84121451, 0.80186734],
       [0.96496273, 0.8799945 , 0.46135838, 0.98831117, 0.01789822],
       [0.92375885, 1.        , 0.0666807 , 0.08219386, 0.99166214],
       [0.        , 0.40422442, 0.88307964, 0.72127053, 0.46064138],
       [0.88790552, 0.7060084 , 0.38422807, 0.62008517, 0.27452709]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [18]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [19]:
x= np.dot(np.ones((5,3)), np.ones((3,2)))
print (x)



[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [20]:
x = np.arange(20)
x[(x >= 3) & (x <= 8)] = -1
x

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

In [21]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(3)
Z ** Z       # = [0^0, 1^1, 2^2] = [1, 1, 4]
2 << Z >> 2  # = [0, 1, 2]
Z < - Z      # = [False, False, False]
1j * Z       # = [0 + 0.j, 0 + 1.j, 0 + 2.j]
Z / 1 / 1    # = [0, 1, 2]
Z < Z > Z    # ValueError

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [23]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [24]:
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)

array([-3.,  5.,  9.,  1.,  3., 10., -6.,  4.,  5.,  7.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [25]:
x = np.arange(0, 10)
y = np.arange(5, 15)
np.intersect1d(x, y)


array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [27]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0




#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [29]:
print(np.sqrt(-1) == np.emath.sqrt(-1)) 

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [33]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow =np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(today)
print(yesterday)
print(tomorrow)

2022-07-23
2022-07-22
2022-07-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [35]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
x


array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [36]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [38]:
x = np.random.uniform(0,10,10)

print(x - x%1)
print(x // 1)
print(np.floor(x))
print(x.astype(int))
print(np.trunc(x))

[5. 6. 1. 7. 3. 6. 8. 1. 2. 6.]
[5. 6. 1. 7. 3. 6. 8. 1. 2. 6.]
[5. 6. 1. 7. 3. 6. 8. 1. 2. 6.]
[5 6 1 7 3 6 8 1 2 6]
[5. 6. 1. 7. 3. 6. 8. 1. 2. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [39]:
x = np.zeros((5, 5))
x += np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [40]:
def generate_integers():
    for i in range(10):
        yield i
np.fromiter(generate_integers(), dtype=np.float32, count=-1)


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [41]:
np.linspace(start=0, stop=11, num=10, endpoint=False)


array([0. , 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [43]:
x = np.random.random(size=10)
x.sort()
x

array([0.12566771, 0.22531259, 0.43783074, 0.54268126, 0.76847909,
       0.87571817, 0.89083846, 0.93025625, 0.93237858, 0.93262317])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [44]:
x = np.arange(10)
np.add.reduce(x)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [49]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
equal2 = np.array_equal(A,B)
print(equal2)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [51]:
x = np.zeros(10)
x.flags.writeable = False
x[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [52]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X ** 2 + Y ** 2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.84681876 0.23383398 1.06179861 0.44251097 0.34171107 0.74355387
 0.21578568 0.40175264 0.48214209 1.27421433]
[0.71200047 0.58648024 1.08613277 1.19248906 0.09186683 1.12408853
 0.99595123 1.40751542 1.37167968 0.70118705]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [56]:
x = np.random.random(10)
print(x)
x[x == np.max(x)] = 0
x[x.argmax()] = 0
x

[0.31151123 0.41331073 0.27180795 0.48134484 0.04971389 0.70517442
 0.92227956 0.49688294 0.87127648 0.86560363]


array([0.31151123, 0.41331073, 0.27180795, 0.48134484, 0.04971389,
       0.70517442, 0.        , 0.49688294, 0.        , 0.86560363])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [58]:
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [59]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / (x - y)
c = 1 / np.subtract.outer(x, y)
np.linalg.det(c)

array([[-6983374.55202571,   -71914.84671783,   -76870.60797373,
          -36473.23476816,   -43967.935857  ],
       [  -76710.56811965,   -96430.06986028,  1184790.01941801,
          -49714.59361086,   -27988.63592294],
       [  -13235.07410426,  -870074.76207318,   -38454.94879274,
          302642.88166773,   -90668.22987724],
       [-1565008.2523898 ,  2260605.5261421 ,   -13348.10131383,
         -236855.32945108,   100272.48273544],
       [  -31425.70636442,  2307673.01849856,  -474009.29924175,
         -894292.26684341,   -70982.93771595]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [60]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [61]:
np.set_printoptions(threshold=float("inf"))
x = np.zeros((40,40))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [62]:
x = np.arange(100)
y = np.random.uniform(0,100)
index = (np.abs(x-y)).argmin()
print(x[index])

75


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [63]:
x = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(x)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [64]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.5422205  0.48457739 0.63618784 0.42326595 0.27217416
  0.36198293 0.34000006 0.44502052 0.37063126]
 [0.5422205  0.         1.00537274 0.53501951 0.31383559 0.76922831
  0.71879272 0.62518798 0.6927093  0.83409962]
 [0.48457739 1.00537274 0.         0.88355743 0.79158881 0.44069111
  0.39343051 0.70493697 0.52059604 0.21833552]
 [0.63618784 0.53501951 0.88355743 0.         0.26771417 0.90380346
  0.49097358 0.92385377 0.37481506 0.66543565]
 [0.42326595 0.31383559 0.79158881 0.26771417 0.         0.69469025
  0.44320975 0.66997784 0.3896923  0.59027719]
 [0.27217416 0.76922831 0.44069111 0.90380346 0.69469025 0.
  0.54342409 0.27599516 0.65940243 0.45835919]
 [0.36198293 0.71879272 0.39343051 0.49097358 0.44320975 0.54342409
  0.         0.69899346 0.1334027  0.17512198]
 [0.34000006 0.62518798 0.70493697 0.92385377 0.66997784 0.27599516
  0.69899346 0.         0.78446198 0.67156169]
 [0.44502052 0.6927093  0.52059604 0.37481506 0.3896923  0.65940243
  0.1334027  0.78446

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [65]:
x = (np.random.rand(10)*100).astype(np.float32)
Y = x.view(np.int32)
Y[:] = x
print(Y)

[14 82 53 64 87 29 34 72  2 60]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [66]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [67]:
x = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(x):
    print(index, value)
for index in np.ndindex(x.shape):
    print(index, x[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [68]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [71]:
n = 10
p = 3
x = np.zeros((n,n))
np.put(x, np.random.choice(range(n*n), p, replace=False),1)
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [73]:
Y = X - X.mean(axis=1, keepdims=True)
Y

array([[-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
         0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
       [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
         0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
       [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
         0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
       [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
         0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
       [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
         0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
       [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
         0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
       [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
         0.11111111,  0.33333333,  0.55555556

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [74]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[7 4 0]
 [7 1 2]
 [5 5 2]]
[[7 1 2]
 [7 4 0]
 [5 5 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [76]:
x = np.random.randint(0,3,(3,10))
print((~x.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [77]:
x = np.random.uniform(0,1,10)
Y = 0.5
m = x.flat[np.abs(x - y).argmin()]
print(m)

0.9358950165476453


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [78]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [80]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)       

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [81]:
x = np.ones(10)
I = np.random.randint(0,len(x),20)
x += np.bincount(I, minlength=len(x))
print(x)

[3. 1. 4. 3. 2. 5. 3. 2. 3. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [82]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [83]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [84]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[49 41 58 75]
 [78 58 37 54]
 [49 49 56 40]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [85]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.45470816 0.42254092 0.51097781 0.50218804 0.4508531  0.41634825
 0.48461564 0.49892389 0.44755001 0.53591658]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [86]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.39159817, 0.71414525, 0.77592144, 1.3262928 , 1.10196159])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [88]:
X = np.array([1,2,3,4,5])
y = 3
x0 = np.zeros(len(x) + (len(x)-1)*(y))
x0[::y+1] = x
print(x0)

[3. 0. 0. 0. 1. 0. 0. 0. 4. 0. 0. 0. 3. 0. 0. 0. 2. 0. 0. 0. 5. 0. 0. 0.
 3. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [89]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [90]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [91]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 8, 71) ( 8, 99) ( 9, 35) ( 9, 65) (11, 30) (11, 54) (24, 50) (24, 84)
 (28, 77) (28, 84) (30, 32) (30, 36) (30, 54) (32, 36) (33, 57) (33, 62)
 (35, 65) (43, 49) (43, 88) (49, 73) (49, 80) (49, 88) (50, 82) (50, 84)
 (50, 90) (57, 62) (71, 99) (73, 80) (77, 84) (82, 90)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [92]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [94]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
x = np.arange(20)
print(moving_average(x, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [96]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
x = rolling(np.arange(10), 3)
print(x)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [97]:
x = np.random.randint(0,2,100)
np.logical_not(x, out=x)

x = np.random.uniform(-1.0,1.0,100)
np.negative(x, out=x)

array([ 0.42798333,  0.0793818 ,  0.66336191, -0.9054    , -0.36984024,
       -0.246984  , -0.61050711, -0.1808896 , -0.74821979, -0.62204002,
       -0.31775521, -0.397088  , -0.55603273,  0.33149885, -0.50587461,
        0.49277872, -0.06269241, -0.66582448,  0.05354685,  0.40953681,
        0.56894349, -0.42626326, -0.37969264,  0.75795025,  0.4829064 ,
       -0.06902024,  0.69610154, -0.05651183,  0.95470009,  0.77574298,
       -0.63038785,  0.66588812,  0.04043449,  0.03188117,  0.43268286,
       -0.85944659,  0.7162609 , -0.10420982,  0.81447606,  0.81732077,
       -0.76398796,  0.70698854,  0.82287117,  0.61739781,  0.13087052,
        0.60907744,  0.12962389,  0.9979531 , -0.93572438,  0.98111029,
       -0.60403665,  0.55145227,  0.43250591, -0.57805155, -0.16364442,
        0.94428363, -0.37728854, -0.90766438, -0.28040897,  0.25997783,
       -0.57440466,  0.11432389, -0.72589628,  0.86519844, -0.00639338,
        0.72214372, -0.49755522,  0.35646204,  0.42188778, -0.02

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [102]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[10.15212901  1.33195222  4.84922547  5.1679712   4.25803377 10.51759387
  9.8909182   7.73989812  9.05525709  3.70685938]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [101]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 8.89630195  6.62219936  5.91966906  1.72948611  4.15757505  5.4866074
   5.27858511  2.52005748  7.75797405  6.3139159 ]
 [ 4.9835455   9.35145325  2.9128537  11.82337086  8.61254361  6.76749507
   0.37448764  9.54984427 17.91081031  3.0152009 ]
 [ 1.62767907 13.98534559  0.8968837   2.40977752 11.3427366   1.42578326
   1.61876387  1.52558026  8.82690689  1.9029426 ]
 [ 1.84613309 17.39031108  2.06971498  3.63345522 14.83089561  4.26731744
   5.09435284  2.60855481 10.22244429  0.84755203]
 [ 9.64721937  6.19880034  8.11318194  0.99878647  3.25484976  4.83400796
   6.52128034  0.42212841  5.03060742  8.66990201]
 [ 7.30217868  7.16444134  0.5074202  10.33149355  6.24358577  8.31696687
   2.07998362  9.63366227 16.31465156  0.69668665]
 [16.72401763  1.01784848 12.76597725  1.28426103  3.71794318 11.7577549
  13.16143787  4.71771293  4.36092681 12.69503353]
 [ 1.12833948 13.40262119  4.85285575 11.03498327 12.35411908  2.51031936
   3.80356534  6.31631312 17.34630539  4.53312937]
 [

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [111]:
x = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

a = np.ones(shape, dtype=x.dtype)*fill
b  = np.array(list(position)).astype(int)
c = np.array(list(a.shape)).astype(int)
d = np.array(list(x.shape)).astype(int)

a_start = np.zeros((len(shape),)).astype(int)
a_stop  = np.array(list(shape)).astype(int)
x_start = (b-c//2)
x_stop  = (b+c//2)+c%2

a_start = (a_start - np.minimum(x_start,0)).tolist()
x_start = (np.maximum(x_start,0)).tolist()
a_stop = np.maximum(a_start, (a_stop - np.maximum(x_stop-d,0))).tolist()
x_stop = (np.minimum(x_stop,d)).tolist()

r = [slice(start,stop) for start,stop in zip(a_start,a_stop)]
e = [slice(start,stop) for start,stop in zip(x_start,x_stop)]
a[r] = x[e]
print(x)
print(a)

[[3 0 3 5 8 9 9 6 3 5]
 [2 9 8 7 2 0 0 3 6 2]
 [3 0 5 8 0 8 8 8 0 4]
 [1 5 4 1 8 9 4 4 5 9]
 [7 7 0 7 5 5 3 4 2 3]
 [9 0 2 2 7 7 6 0 1 6]
 [1 3 2 2 1 9 0 8 7 5]
 [0 5 2 7 0 1 7 3 9 6]
 [6 2 9 0 5 2 9 2 7 6]
 [7 8 5 4 6 7 6 9 4 8]]
[[0 0 0 0 0]
 [0 3 0 3 5]
 [0 2 9 8 7]
 [0 3 0 5 8]
 [0 1 5 4 1]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [112]:
x = np.arange(1,15,dtype=np.uint32)
y = stride_tricks.as_strided(x,(11,4),(4,4))
print(y)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [114]:
x = np.random.uniform(0,1,(10,10))
a, b, c = np.linalg.svd(x) 
rank = np.sum(b > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [117]:
x = np.random.randint(0,10,20)
print(np.bincount(x).argmax())

2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [118]:
x = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (x.shape[0]-3)
j = 1 + (x.shape[1]-3)
C = stride_tricks.as_strided(x, shape=(i, j, n, n), strides=x.strides + x.strides)
print(C)

[[[[1 4 3]
   [2 1 4]
   [3 1 2]]

  [[4 3 4]
   [1 4 3]
   [1 2 4]]

  [[3 4 4]
   [4 3 4]
   [2 4 4]]

  [[4 4 2]
   [3 4 2]
   [4 4 0]]

  [[4 2 4]
   [4 2 0]
   [4 0 3]]

  [[2 4 3]
   [2 0 1]
   [0 3 2]]

  [[4 3 3]
   [0 1 3]
   [3 2 4]]

  [[3 3 3]
   [1 3 0]
   [2 4 3]]]


 [[[2 1 4]
   [3 1 2]
   [4 4 0]]

  [[1 4 3]
   [1 2 4]
   [4 0 4]]

  [[4 3 4]
   [2 4 4]
   [0 4 2]]

  [[3 4 2]
   [4 4 0]
   [4 2 2]]

  [[4 2 0]
   [4 0 3]
   [2 2 3]]

  [[2 0 1]
   [0 3 2]
   [2 3 2]]

  [[0 1 3]
   [3 2 4]
   [3 2 2]]

  [[1 3 0]
   [2 4 3]
   [2 2 2]]]


 [[[3 1 2]
   [4 4 0]
   [0 4 3]]

  [[1 2 4]
   [4 0 4]
   [4 3 4]]

  [[2 4 4]
   [0 4 2]
   [3 4 2]]

  [[4 4 0]
   [4 2 2]
   [4 2 0]]

  [[4 0 3]
   [2 2 3]
   [2 0 2]]

  [[0 3 2]
   [2 3 2]
   [0 2 4]]

  [[3 2 4]
   [3 2 2]
   [2 4 4]]

  [[2 4 3]
   [2 2 2]
   [4 4 4]]]


 [[[4 4 0]
   [0 4 3]
   [4 2 4]]

  [[4 0 4]
   [4 3 4]
   [2 4 3]]

  [[0 4 2]
   [3 4 2]
   [4 3 4]]

  [[4 2 2]
   [4 2 0]
   [3 4 3]]

  [[2 2 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [120]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(x):
    return np.asarray(x + x.T - np.diag(x.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6  7  6  7 12]
 [ 7  2  9 10  7]
 [ 6  9  6 42  5]
 [ 7 10 42  5  7]
 [12  7  5  7  4]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [121]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [123]:
x = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(x, np.arange(0, x.shape[0], k), axis=0),
                                       np.arange(0, x.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [124]:
def iterate(x):
    
    N = (x[0:-2,0:-2] + x[0:-2,1:-1] + x[0:-2,2:] +
         x[1:-1,0:-2]                + x[1:-1,2:] +
         x[2:  ,0:-2] + x[2:  ,1:-1] + x[2:  ,2:])

    
    birth = (N==3) & (x[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (x[1:-1,1:-1]==1)
    x[...] = 0
    x[1:-1,1:-1][birth | survive] = 1
    return x

x = np.random.randint(0,2,(50,50))
for i in range(100): x = iterate(x)
print(x)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 1 0 0 1 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 1 1 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [127]:
x = np.arange(10000)
np.random.shuffle(x)
n = 5
print (x[np.argsort(x)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [128]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [129]:
x = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
y = np.core.records.fromarrays(x.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(y)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [130]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.71 s per loop
10 loops, best of 5: 135 ms per loop
10 loops, best of 5: 120 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [131]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [132]:
x = np.random.randint(0,5,(10,3))
print(x)

a = np.all(x[:,1:] == x[:,:-1], axis=1)
b = x[~a]
print(b)

b = x[x.max(axis=1) != x.min(axis=1),:]
print(b)

[[0 4 2]
 [0 4 0]
 [4 3 0]
 [0 1 0]
 [1 2 3]
 [4 1 1]
 [4 0 3]
 [2 4 1]
 [2 4 3]
 [1 3 1]]
[[0 4 2]
 [0 4 0]
 [4 3 0]
 [0 1 0]
 [1 2 3]
 [4 1 1]
 [4 0 3]
 [2 4 1]
 [2 4 3]
 [1 3 1]]
[[0 4 2]
 [0 4 0]
 [4 3 0]
 [0 1 0]
 [1 2 3]
 [4 1 1]
 [4 0 3]
 [2 4 1]
 [2 4 3]
 [1 3 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [134]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [135]:
x = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(x).view(np.dtype((np.void, x.dtype.itemsize * x.shape[1])))
_, idx = np.unique(T, return_index=True)
d = x[idx]
print(d)

[[0 0 1]
 [0 1 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [137]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)    

array([[0.47623281, 0.10688661, 0.34535934, 0.10919614, 0.69966421,
        0.62009124, 0.60372813, 0.73264688, 0.4737665 , 0.10553227],
       [0.52486913, 0.11780264, 0.38062992, 0.12034804, 0.77111896,
        0.68341942, 0.66538519, 0.80747005, 0.52215094, 0.11630998],
       [0.22938838, 0.05148437, 0.16635019, 0.05259681, 0.3370092 ,
        0.29868107, 0.2907994 , 0.35289605, 0.22820042, 0.05083202],
       [0.51312639, 0.11516708, 0.3721142 , 0.11765553, 0.75386695,
        0.66812949, 0.65049873, 0.78940477, 0.51046902, 0.11370782],
       [0.20456431, 0.04591281, 0.14834802, 0.04690486, 0.30053857,
        0.26635825, 0.25932953, 0.31470617, 0.20350492, 0.04533106],
       [0.17561485, 0.03941534, 0.12735416, 0.040267  , 0.25800706,
        0.22866386, 0.22262982, 0.27016969, 0.17470538, 0.03891591],
       [0.19937138, 0.0447473 , 0.14458216, 0.04571416, 0.2929093 ,
        0.25959665, 0.25274636, 0.30671725, 0.19833887, 0.04418031],
       [0.24484839, 0.05495425, 0.1775616

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [139]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [140]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [141]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.21478915  0.16001129]
